### PR TITLE
Start conversation on new logging library

### PR DESCRIPTION
**Pull request by jveldboom-rsc**
This is to start the conversation on implementing a new logging format. Choosing JSON in expectations of the AWS announcement this week on CloudWatch Logs.

This is a quick rough draft but hopefully will help get the idea across to start the conversation. Feel free to adjust and change until we get this to a good spot.

I'm choosing to not use a library to keep it simple. The popular logging libraries seem to do a lot - while we really just need a standard wrapper for `console.log()` - similar to our `clean-log` library.

### CODE REVIEW

**Comment by rsc-rfrench** [comment]
I'm not convinced it would be a good choice for logging, but I wanted to contrast what you have with some of the features of jsonapi:

* Per https://jsonapi.org/format/#document-top-level, a jsonapi document will contain either an `errors` field or a `data` field. I think this property would help filtering, and perhaps we could get something similar with a rule that says "Messages with level 'error' will contain an `errorMsg` field but not a `msg` field". Or we could just infer that `error` level messages will put their error data in the `msg` field
* Per https://jsonapi.org/format/#document-resource-object-attributes, the *content* of a message is separated somewhat from the navigational / type aspects of a message. I think we could get a similar aesthetic by having `log.warn('Not too serious', { userId: 1, name: 'John Doe'} )` yield something like `{"level": "warn", "msg": "Not too serious", "attributes":  { userId: 1, name: 'John Doe'}}`

I am experiencing a gut feeling that having something akin to those features would help us write better filtering logic, but I don't know how strongly I can justify this feeling.

**Comment by rsc-rfrench** [comment]
Further, can you help me understand the use case of logging both a message and an object? Do you have any strong feelings about an interface like this:

* `log.warn({ an: 'object' })` --> `{"level": "warn", "msg": { "an": "object" }}`
* `log.warn('a string')` --> `{"level": "warn", "msg": "a string"}`

**Comment by jveldboom-rsc** [comment]
Thank you for the feedback. This is exactly the conversation I was hoping for!

- I like the idea of having a single `msg` field. Think that will make querying on it later easier and consistent.
- Really like using `attributes` instead of trying to flatten the object. Believe this will also allow flexibility in logging and querying later. Also, something I did not think about here is it would be possible to overwrite an attribute with `log.warning('my-warning', { level: 'fake! '})` So win-win here!
- For the `msg` field, I think keeping that a string will make the interface easier to use. Since we have the above `attribute` field, I do not think we need another place to drop drop objects. Also think acception objects here could make it difficult to query later with no real benefit.

I think most of queries are going to be on the log `level` first. And then secondly aggregations on the `msg` text. Then third on the attributes.

**Comment by jveldboom-rsc** [comment]
Rethought the interface a little more and I think I like this for the interface when passing an `Error` object. I believe this will be the most common use case for the library and will allow you to pass the error object directly in without having to construct the object.

```js
let err = new Error(`my-error-message`)
log.error(`my-error`, err)
// {"level":"error","message":"my-error","attributes":{"errorMessage":"my-error-message"}}

// vs having to construct the object - which you *could* still do
log.error(`my-error`, { errorMessage: err.message })
```

Also, leaning towards not abbreviating the fields. So using `message` instead of `msg`. And `attributes` instead of `attrs`. 

Open to suggestions on the `errorMessage`. Maybe just `error` with the error message. Or having the whole error object - message, code and stack ?

**Comment by rsc-rfrench** [comment]
> I think most of queries are going to be on the log `level` first. And then secondly aggregations on the `msg` text. Then third on the attributes.

This makes a lot of sense, and I think it's worth using that statement as a rubric by which to evaluate design choices.

---

Regarding `log.error('my-error', err)`, I want to double check something that I think you are hinting at: do you mean to suggest to users that the first field should be less of a free-form message body and more like a "tag" or "enum"? For example, let's say I am handling errors in a couple of places, I could do:

```javascript
// module A
log.error('network error', err)

// module B
log.error('could not connect', {ip: "8.8.8.8"})
```

but this would be hard to aggregate, because I *probably* mean the same thing by 'network error' and 'could not connect'. It seems like the user would be better off with something (that I think you outlined) like

```javascript
// module A
log.error('connection', err)

// module B
log.error('connection', {ip: "8.8.8.8"})
```

which would allow for better aggregation on the string 'connection'. In Ruby, there is a concept of a "Symbol", which is effectively a global singleton string. It is really handy for stuff like this because you can say:

```ruby
:network_error = "Network Error"

# module A
log.error :network_error, err

# module B
log.error :network_error, {:ip => "8.8.8.8"}
```

So I reckon my questions are:

* Is that what you had in mind?
* If so, is there something we can do with the interface that would suggest this usage pattern to the user so that their natural inclination is to do the thing that will make aggregation easiest? Maybe it would be as simple as calling this argument "tag" instead of "msg"?

---

> Also, leaning towards not abbreviating the fields. So using message instead of msg. And attributes instead of attrs.

I support this 100%. Storage is cheaper than confusion by several orders of magnitude.

---

> Open to suggestions on the errorMessage. Maybe just error with the error message. Or having the whole error object - message, code and stack ?

What if it was an arbitrary object, and the handling algorithm looked something like this:
* If it's of type `Error`, print the stack trace and return
* If `JSON.stringify` doesn't throw an exception, print its output and return
* Fall back to the object's `toString` method

I think that would allow users to throw in whatever object is easiest to reach, rather than needing to do any transformations at a problem site.

**Comment by rsc-rfrench** [comment]
I think this is lookin *real good*

**Comment by jveldboom-rsc** [comment]
> that the first field should be less of a free-form message body and more like a "tag" or "enum"?

While I think that could be useful, I do not want dictate or maintain a list of valid tags in the library. But rather just keep the first field as free-form text. I feel like the tags would be so varied upon each application that it would be difficult to keep up with them and people would end up writing their own anyway.

But in saying that we could encourage people to use constants in their application to prevent the same `message` being written 5 different ways. Not sure if just adding a "Best Practices" in the docs or actually building a way to include tags. Leaning towards just in the docs for now but maybe add later?

Something like this:
```js
// logTags.js
module.exports = {
  NETWORK_ERROR: `network error`,
  DB_ERROR: `database error`,
  TIMEOUT: `request timeout`
}

....

let logTags = require('./logTags')
log.info(logTags.NETWORK_ERROR, err}
```
---

> What if it was an arbitrary object, and the handling algorithm looked something like this:

Not sure I understand the implementation so let correct me if I'm wrong here.

```js
...
format(level, message, attributes) {
    
    if (typeof message !== 'string') message = JSON.stringify(message)

    if (attributes instanceof Error) {
        attributes = { 
            error: attributes.message,
            stack: attributes.stack
        }
    }
    else if (typeof attributes === 'string') attributes = { attributes }

    this.logLine = JSON.stringify({
        level,
        message,
        attributes
    })

    return this
},
...
```

---

To flesh out a use case...

Recently, I've been writing my logs like this with the `clean-log` library:
```js
log.error(`Unable to find get ${userId} in db because ${err.message}`)
```

With this new library, this would be written which I think is a pretty good interface:
```js
log.error(logTags.DB_ERROR, { userId, error: err.message })
```

**Comment by rsc-rfrench** [comment]
Absolutely, I think that all makes sense. And I agree, the library should not try to maintain the tags, I just wanted to see if you thought that would make sense for folks to think of doing on their own. I think providing an example in the docs like you outlined above would be a big win.

---

I think the handling code you outlined above makes sense; I was interpreting the parameters a little differently. For example, this is a use case from from handling http requests:

```javascript
someFunc(arg1, arg2, (err, data) => {
    if (err) log.error('network-error', err)
    if (data.status == 500) log.error('service-error', data)
})
```

where `err` is an `Error` object, but `data` is just some arbitrary object returned from `someFunc`. *If* that were a supported interface, we could handle it like this:

```javascript
format(level, message, attributes) {
    
    // Just assume 'message' is a string, or maybe bother asserting if we really care

    if (attributes instanceof Error) {
        attributes = { 
            error: attributes.message,
            stack: attributes.stack
        }
    }

    try {
        this.logLine = JSON.stringify({
            level,
            message,
            attributes
        })
    } catch {
        // Assume that 'attributes' was the offender, since 'level' and 'message' are strings
       this.logLine = JSON.stringify({
            level,
            message,
            attributes.toString()
        })
    }

    return this
},
```

The issue here is that if attributes contains a cycle, JSON.stringify will barf. If we want users to be able to pass in arbitrary objects, we will need to account for that. If we think it's sufficient to put the onus on them to pass only plain objects, we can ignore that.

**Comment by jveldboom-rsc** [comment]
Good catch on the circular reference.

Quick way to set a circular reference - keeping it here for reference to be used in testing later
```js
let data = [];
data[0] = data;
log.error(`my-error`, data)
```

---

How about this?

Here are some summary:

- `level` & `message` must be strings
- `attributes` is optional but can be string `attributes: 'my-string'` or object `attributes: { key: value }`
  - Initially I was going to force `attributes` to always be an object because I was thinking of the way Elasticseach's mappings work. Still not 100% sure but let's use the above for now.
```js
format(level, message, attributes) {

  // move everything within try/catch
  try {
    if (attributes instanceof Error) {
      attributes = {
        error: attributes.message,
        stack: attributes.stack
      }
    }
    // remove empty object & array
    else if (attributes && !Object.keys(attributes).length) {
      attributes = undefined
    }
    
    this.logLine = JSON.stringify({
      level: level.toString(),
      message: message.toString(),
      attributes
    })

  } catch (err) {

    // log error here?
    // log.error(`logging error`, err)

    // catch circular reference and other exception
    this.logLine = JSON.stringify({
      level,
      message,
      attributes: { 
        logError: err.message 
      }
    })
  }

  return this
},
```

**Review by tbrown-rsc — APPROVED** [review]
Lots of good content and discussion.  I’m really liking this new library!

**Comment by jveldboom-rsc** [comment]
Merging into master to move forward with publishing this as a npm module. Will make adjustments as needed

**Pull request merged**
